baseurl = "https://trang.rbind.io/"
title = "Trang Nguyen"
author = "Trang Nguyen"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"
enableEmoji = true
hasCJKLanguage = true

googleAnalytics = "UA-147123435-1"


disqusShortname = "blog-ehhnsgt6og"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
      
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]


[params]
pagetitle = "Trang Nguyen"
copyright = "Â© 2021 Trang Nguyen"

copyrightUrl = "/"
email = "ng.trang.ds@gmail.com"
faviconfile = "image/favicon.png"
github = "trang-n"
twitter = "trangsfigure"
linkedin = "trang-n"
logofile = "image/logo.jpg" 
highlightjs = true
posts_navigation = true
progressively = false
uselatex = true
  
[[menu.primary]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 4

[[menu.primary]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 1


[[menu.primary]]
  identifier = "canon"
  name = "Personal Canon"
  url = "/canon/"
  weight = 2


[[menu.primary]]
  identifier = "recent"
  name = "Recent Interests"
  url = "/recent/"
  weight = 3

[[menu.primary]]
  identifier = "contact"
  name = "Get In Touch"
  url = "/contact/"
  weight = 5

